version: '2'
services:
  cache:
    image: redis:3.2.1-alpine
  app:
    build: .
    env_file:
      - ./web.env
    environment:
      MAX_REQUESTS: 1000000
      DB_NAME: cpsc310
      WORKERS: 3
      CMD_SCRIPT: 'app.sh'
    volumes:
      # expose the host docker socket
      # any containers started inside of job will run on the host as a sibiling container
      - /var/run/docker.sock:/var/run/docker.sock
      - /repos:/repos:z
    privileged: true
    ports:
      - "3000:3000"
    links:
      - cache
  db:
    image: couchdb:1.6.1
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: 'password'
    ports:
      - "5984:5984"
