version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
  db:
    image: couchdb:1.6.1
  nginx:
    build:
      context: ./nginx
    links:
      - web
      - db
  web:
    image: cpsc310-pullrequest-server
    build:
      context: ./pull-request
    ports:
      - "4430:4430"
    links:
      - redis
