version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
  db:
    image: couchdb:1.6.1
  web:
    build: ./pull-request
    expose:
      - "4430"
    links:
      - redis
  nginx:
    build: ./nginx
    ports:
      - "443"
    links:
      - web
      - db
