version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
  web:
    image: cpsc310-pullrequest-server
    build:
      context: ./pull-request
    ports:
      - "4430:4430"
    environment:
      REDIS_HOST: redis
    links:
      - redis
    depends_on:
      - redis
