version: '2'
services:
  cache:
    image: redis:3.2.1-alpine
  db:
    image: couchdb:1.6.1
    env_file:
      - ./db.env
    volumes:
      - db-data:/usr/local/var/lib/couchdb
  app:
    build: ./app
    env_file:
      - ./web.env
    environment:
      MAX_REQUESTS: 1000000
      DB_NAME: cpsc310
      WORKERS: 3
      TEST_REPO_URL: 'https://github.com/nickbradley/cpsc310-tester.git'
      TEST_REPO_URLS: 'URL_1'
      CMD_SCRIPT: 'runTest.sh'
    volumes:
      # expose the host docker socket
      # any containers started inside of job will run on the host as a sibiling container
      - /var/run/docker.sock:/var/run/docker.sock
      - /repos:/repos:z
    privileged: true
    links:
      - cache
  proxy:
    build: ./nginx
    ports:
      - "443:443"
    links:
      - app
      - db

volumes:
  db-data:
    external:
      name: cpsc310-couchdb-store
