version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
  db:
    image: couchdb:1.6.1
    volumes:
      - cpsc310-couchdb-store:/usr/local/var/lib/couchdb
  job:
    build: ./job-runner
  web:
    build: ./pull-request
    links:
      - redis
      - job
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    links:
      - web
      - db

  volumes:
    cpsc310-couchdb-store:
      external: true
