version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
  db:
    image: couchdb:1.6.1
    env_file:
      - ./db.env
    volumes:
      - db-data:/usr/local/var/lib/couchdb
  job:
    build: ./job-runner
    volumes:
      # expose the host docker socket
      # any containers started inside of job will run on the host as a sibiling container
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  web:
    build: ./pull-request
    env_file:
      - ./web.env
    environment:
      MAX_REQUESTS: 10
      DB_NAME: cpsc310
    links:
      - redis
      - job
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    links:
      - web
      - db

volumes:
  db-data:
    external:
      name: cpsc310-couchdb-store
