version: '2'
services:
  cache:
    image: redis:3.2.1-alpine
  app:
    build: .
    env_file:
      - ./app.env
    volumes:
      # expose the host docker socket
      # any containers started inside of job will run on the host as a sibiling container
      - /var/run/docker.sock:/var/run/docker.sock
      - /repos:/repos:z
    privileged: true
    ports:
      - "8080:8080"
    links:
      - cache
      - db
  db:
    image: couchdb:1.6.1
    env_file:
      - ./app.env
    ports:
      - "5984:5984"
    volumes:
      - db-data:/usr/local/var/lib/couchdb

volumes:
  db-data:
    external:
      name: cpsc310-couchdb-store
