version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
  db:
    image: couchdb:1.6.1
  web:
    image: cpsc310-pullrequest-server
    build: ./pull-request
    ports:
      - "4430:4430"
    links:
      - redis
  nginx:
    build: ./nginx
    links:
      - web
      - db
