FROM nginx:1.10-alpine
MAINTAINER Nick Bradley <nbrad11@cs.ubc.ca>

COPY nginx.conf /etc/nginx/nginx.conf
COPY cpsc310-2016Fall.crt /etc/ssl/certs/cpsc310-2016Fall.crt
COPY cpsc310-2016Fall.key /etc/ssl/certs/cpsc310-2016Fall.key
